on:
  push:
    branches: [ ignnition-nightly ]
  pull_request:
    branches: [ ignnition-nightly ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PYTHONPATH: /home/runner/work/ignnition

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: test ls
      run: |
        ls

    - name: Run example tests with pytest
      run: |
        pytest
